sudo sysrepoctl -i O-RAN/o-ran-wg4-features.yang -v3
sudo sysrepoctl -i O-RAN/o-ran-certificates.yang -v3
sudo sysrepoctl -i O-RAN/o-ran-fan.yang -v3
sudo sysrepoctl -i O-RAN/o-ran-fm.yang -v3
#sudo sysrepoctl -i O-RAN/o-ran-hardware.yang -v3
sudo sysrepoctl -i O-RAN/o-ran-ves-subscribed-notifications.yang -v3
sudo sysrepoctl -i Others/iana-hardware.yang -v3
sudo sysrepoctl -i Others/ietf-hardware.yang -v3
sudo sysrepoctl -i O-RAN/o-ran-hardware.yang -v3
sudo sysrepoctl -i O-RAN/o-ran-usermgmt.yang -v3
sudo sysrepoctl -i O-RAN/o-ran-supervision.yang -v3
sudo sysrepoctl -i Others/iana-if-type.yang -v3
sudo sysrepoctl -i O-RAN/o-ran-interfaces.yang -v3
sudo sysrepoctl -i O-RAN/o-ran-sync.yang -v3
